### ISSUE TITLE
Regression in new version - incorrect wallpaper scaling

### ISSUE THREAD

**Issue by aleksanderkrauze** [LGFae/swww#433]
Hello. I'm running `hyprland` with `swww` on Fedora and use fractional display scaling.  A couple days ago I upgraded `swww` to the newest version (`0.10.0`). After doing so `swww` started to use wrong scaling which results in wallpaper being display as a minature in the center.

This seems to be a duplicate of #285, which was closed as solved in release `0.9.4`. This break happened to me when I upgraded from `0.9.5` to `0.10.0`, therefore I assume this is a regression.

Here is my configuration:

```
$ hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1200@60.00100 at 0x0
	description: Lenovo Group Limited 0x403A
	make: Lenovo Group Limited
	model: 0x403A
	serial: 
	active workspace: 4 (4)
	special workspace: 0 ()
	reserved: 0 33 0 0
	scale: 1.25
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	directScanoutTo: 0
	disabled: false
	currentFormat: XRGB8888
	mirrorOf: none
	availableModes: 1920x1200@60.00Hz 1920x1080@60.00Hz 1600x1200@60.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz 
```

```
$ swww query      
eDP-1: 960x600, scale: 2, currently displaying: image: /home/akrauze/Pictures/wallpapers/Northern Lights3.png
```

And here is a screenshot of how it is being rendered:

![Image](https://github.com/user-attachments/assets/31bf11cd-feac-4fcf-aa53-d0e5e9881247)

**Comment by LGFae** [comment]
I will be closing this for now, with the latest release, as it should be fixed. Feel free to reopen it.

**Comment by NischalDawadi** [comment]
Still same issue when using 0.10.1

![Image](https://github.com/user-attachments/assets/385bf431-46a3-46f5-9e68-0c04ae8f1354)

**Comment by hotsno** [comment]
Yep, I'm also experiencing this on Hyprland. Here's my minimal hyprland config:

```
$terminal = kitty
bind = super, return, exec, $terminal
bind = super, q, killactive,
bind = super shift, q, exit,

exec-once = swww-daemon
```

Then after running `hyprctl reload` I get the incorrectly scaled wallpaper. It seems like there are other triggers, not just `hyprctl reload`, but that's the one I've found for now

**Comment by littleblack111** [comment]
> This should be solved in the latest git version, by [#429](https://github.com/LGFae/swww/pull/429). I would appreciate if you could test it there.

nope, tried latest -git on arch, still have this problem, package from extra repo with version 0.9.5 had no issue

**Comment by MeshVoid** [comment]
I think I might have a similar problem... Can it be hyprland related specifically related to the latest hyprland update?

**Comment by AshnageNarnesfugen** [comment]
wow, you were right, manually changing them fixes the issue, i'll do some tests

**Comment by eylles** [comment]
hi, i'm forwarding this issue from [pywal16](https://github.com/eylles/pywal16/issues/172), user @givtrah was having this bug when pywal sets the wallpaper with swww, internally what pywal16 does is:
https://github.com/eylles/pywal16/blob/d1ff9b9ba3df17ceda734953b57fd16474cfbafd/pywal/wallpaper.py#L75-L76

which should for all intents become: `swww img /path/to/image` 

quoting from the issue:

>I set my wallpaper using swww, which works perfectly.
>
>Before running pywal16 I get
>
>~ ❯ swww query
>DP-1: 2560x1440, scale: 1.5, currently displaying: color: 000000
>DP-2: 2560x1440, scale: 1.5, currently displaying: color: 000000
>
>I then run pywal16 as:
>
>wal --cols16 lighten -i image.jpg
>
>after which my viewport (or whatever its called) decreases in size and my wallpaper now no longer takes up the full screen!
>
>~ ❯ swww query
>DP-1: 1920x1080, scale: 2, currently displaying: color: 000000
>DP-2: 1920x1080, scale: 2, currently displaying: color: 000000
>
>In other words, by running pywal16 it has changed the scaling of my display / viewport size.

from the rest of the comments in this issue my guess is this ought to be a heisenbug that has hyprland and non-interactive shells as common denominators, wish i could help more than just this but i neither program in rust nor use wayland.

**Comment by dillacorn** [comment]
I was trying to work this out for a few hours myself... thought I was doing something wrong but defiantly an issue that needs to be resolved..

display scaling 1.0 works and as mentioned 2.0 works.. but anything in between gives you a scaled down centered image which isn't desirable especially if you include the --resize crop flag (default when not included)

I have resorted to killing swww-daemon and then launching it again which temporary resolves it.. not pretty though.. when waking from sleep the issue appears as well.

**Comment by chupsondev** [comment]
> Can someone please confirm whether [#439](https://github.com/LGFae/swww/pull/439) fixes the problem for you?

Yup, worked for me, thanks
